# Generated by Django 2.1.5 on 2021-06-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rooms_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomcategory',
            old_name='name',
            new_name='category_name',
        ),
    ]
