# Generated by Django 2.1.5 on 2021-06-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_reserve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
