# Generated by Django 2.1.5 on 2021-06-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_delete_reserve'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.CharField(blank=True, choices=[('Room Service 24/7', 'room service 24/7'), ('Airport Shuttle', 'airport shuttle'), ('Laundry Service 24/7', 'laundry service 24/7'), ('Free WiFi', 'free wifi')], max_length=30, null=True),
        ),
    ]
