# Generated by Django 2.1.5 on 2021-06-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210619_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
    ]
