# Generated by Django 2.1.5 on 2021-06-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20210619_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image1', models.ImageField(null=True, upload_to='rooms/')),
                ('image2', models.ImageField(null=True, upload_to='rooms/')),
                ('image3', models.ImageField(null=True, upload_to='rooms/')),
            ],
            options={
                'verbose_name': 'Homepage Description',
                'verbose_name_plural': 'Homepage Descriptions',
            },
        ),
    ]
