# Generated by Django 2.1.5 on 2021-06-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='room_type',
            new_name='room_category',
        ),
    ]
