# Generated by Django 2.1.5 on 2021-06-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20210622_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='rooms',
            name='image2',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image3',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image4',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='image5',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
