# Generated by Django 2.1.5 on 2021-06-24 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20210623_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('image1', models.ImageField(null=True, upload_to='rooms/')),
            ],
            options={
                'verbose_name': 'Комната  photo',
                'verbose_name_plural': 'room photos',
            },
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={},
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='image5',
        ),
        migrations.AddField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms'),
        ),
    ]
