# Generated by Django 2.1.5 on 2021-06-24 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_auto_20210624_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomphoto',
            options={'verbose_name': 'Room  photo', 'verbose_name_plural': 'Room photos'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='roomphoto',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='rooms.Rooms'),
        ),
    ]
